[project]
name = "guardrails-intro"
version = "0.1.0"
description = "Introduction to the use of guardrails for Generative AI applications"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
